version: '3'
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile  # Path to your Dockerfile
    ports:
      - "8080:80"  # Map port 80 in the container to port 8080 on the host
    volumes:
      - ./local_charts:/app/charts  # Map a local directory to /app/data in the container
    environment:
      - NAME=World
      - API_PORT=80
